[hotfix/browser timeout] 활당 컨텍스트를 주기적으로 캔슬하게끔 코딩
s-owl/skhus-backend pull request #48
Opened 2019-09-30 10:00 UTC by tpdns90321

2019-10-01 03:36 UTC, sukso96100 requested changes
라인에 단 커멘트 참고

2019-10-01 03:36 UTC, sukso96100 commented on browser/browser.go
> +			chromedp.NewExecAllocator(context.Background(), opts...)
`NewExecAllocator()`호출 후 ` NewContext()` 를 반드시 호출 해줘야만 브라우저가 생성됨.

2019-10-01 03:36 UTC, sukso96100 commented on browser/browser.go
> +	return brow.allocCtx != nil
아래와 같은 코드로 컨텍스트 정상 생성 되었는지 확인하는 코드 추가하는 것도 추가로 고려하기.
```go
// ensure the first tab is created
if err := chromedp.Run(ctx1); err != nil {
    panic(err)
}
```

참고
https://github.com/chromedp/chromedp/issues/454

2019-10-01 05:16 UTC, tpdns90321 commented
skhus 프로그램 문제인지 크롬 문제인지 확인하지 않고 시도한 건데 일단 process 디버그를 일단 해봐야겠네요

2019-10-02 01:03 UTC, tpdns90321 commented on browser/browser.go
> +			chromedp.NewExecAllocator(context.Background(), opts...)
tab 컨텍스트를 종료를 하지만 계속 남아있어서 주기적으로 할당 컨텍스트를 꺼야 할 것 같습니다. 혹시 실수로 컨텍스트 닫지 않은 것 있는지 확인이 필요해보입니다.

2019-10-02 01:20 UTC, tpdns90321 commented on browser/browser.go
> +	return brow.allocCtx != nil
NewContext method에 추가하는 게 맞는 것 같습니다.

2019-10-02 01:21 UTC, tpdns90321 commented
WaitGroup 과 Mutex 쓰는 것으로 바꾸겠습니다. 너무 더럽게 코딩했어

2019-10-02 07:44 UTC, tpdns90321 commented on browser/browser.go
> +	return brow.allocCtx != nil
생각해보니 이거는 chromedp.Run 을 실행할 때 간단하게 에러 핸들링만 하면 될 것 같을 것 같네요

2019-10-02 09:26 UTC, sukso96100 approved these changes

2019-10-02 09:26 UTC, merged